name       : python-platformdirs
version    : 2.2.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/platformdirs/platformdirs-2.2.0.tar.gz : 632daad3ab546bd8e6af0537d09805cec458dce201bccfe23012df73332e181e
license    : MIT
component  : programming.python
summary    : A small Python module for determining appropriate platform-specific dirs
description: |
    A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
builddeps  :
    - python-pytest-mock # check
    - python-setuptools-scm
    - python-wheel
setup      : |
    sed -i '3 i\Version: %version%' setup.cfg
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
