name       : python-platformdirs
version    : 2.5.3
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/p/platformdirs/platformdirs-2.5.3.tar.gz : 6e52c21afff35cb659c6e52d8b4d61b9bd544557180440538f255d9382c8cbe0
homepage   : https://github.com/platformdirs/platformdirs
license    : MIT
component  : programming.python
summary    : A small Python module for determining appropriate platform-specific dirs
description: |
    platformdirs is a library to determine platform-specific system directories. This includes directories where to place cache files, user data, configuration, etc.
builddeps  :
    - python-appdirs        # check
    - python-build
    - python-hatch-vcs
    - python-installer
    - python-pytest-mock    # check
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
