name       : python-platformdirs
version    : 2.6.2
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/p/platformdirs/platformdirs-2.6.2.tar.gz : e1fea1fe471b9ff8332e229df3cb7de4f53eeea4998d3b6bfff542115e998bd2
homepage   : https://github.com/platformdirs/platformdirs
license    : MIT
component  : programming.python
summary    : A small Python module for determining appropriate platform-specific dirs
description: |
    platformdirs is a library to determine platform-specific system directories. This includes directories where to place cache files, user data, configuration, etc.
builddeps  :
    - python-appdirs        # check
    - python-build
    - python-hatch-vcs
    - python-installer
    - python-pytest-mock    # check
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
