name       : python-platformdirs
version    : 2.4.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/platformdirs/platformdirs-2.4.1.tar.gz : 440633ddfebcc36264232365d7840a970e75e1018d15b4327d11f91909045fda
license    : MIT
component  : programming.python
summary    : A small Python module for determining appropriate platform-specific dirs
description: |
    A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
builddeps  :
    - python-pytest-mock # check
    - python-setuptools-scm
    - python-wheel
setup      : |
    sed -i '3 i\Version: %version%' setup.cfg
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
