name       : python-platformdirs
version    : 2.5.2
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/p/platformdirs/platformdirs-2.5.2.tar.gz : 58c8abb07dcb441e6ee4b11d8df0ac856038f944ab98b7be6b27b2a3c7feef19
homepage   : https://github.com/platformdirs/platformdirs
license    : MIT
component  : programming.python
summary    : A small Python module for determining appropriate platform-specific dirs
description: |
    platformdirs is a library to determine platform-specific system directories. This includes directories where to place cache files, user data, configuration, etc.
builddeps  :
    - python-appdirs        # check
    - python-build
    - python-hatch-vcs
    - python-installer
    - python-pytest-mock    # check
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
